# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.terminologie
canonical: https://interop.esante.gouv.fr/ig/terminologie
name: NOS
title: Terminologies  de Santé (Publiées par l'ANS)
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
description: Les nomenclatures des objets de Santé sont mises à disposition du secteur santé-social par l’agence du numérique en santé
version: 1.1.0
date: 2023-03
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
    shownav: 'true'
    path-resource:
        - input/NOS/JDV
        - input/NOS/TRE


pages:
    index.xml:
        title: Accueil
    nos.md:
        title : NOS     
    tre.xml:
        title :  Terminologies de référence 
    telechargement-tre.xml:
        title :  Terminologies de référence      
    jdv.xml:
        title :  Jeux de valeurs 
    telechargement-jdv.xml:
        title :  Jeux de valeurs            
    ass.xml:
        title :  Association 
    telechargement-ass.xml:
        title :  Association       
    smt.md:
        title :   Terminologie          
    autres_ressources.md:
        title: Autres Ressources
        telechargementNos.md:
            title :   téléchargement (NOS)           
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    NOS : nos.html
    Terminologies de référence  : tre.html
    Jeux de valeurs  : jdv.html
    Association  : ass.html
    Terminologie : smt.html
    Ressources:
        Téléchargement (NOS) : telechargementNos.html
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html
