# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.terminologie
canonical: https://interop.esante.gouv.fr/ig/terminologie
name: Terminologie
title: Terminologies  de Santé (Publiées par l'ANS)
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
description: Les nomenclatures des objets de Santé sont mises à disposition du secteur santé-social par l’agence du numérique en santé
version: 1.1.0

date: 2023-03
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "France"



parameters:
    apply-version: false
    shownav: 'true'
    path-resource:
        - DM/fsh-generated/resources
        - input/ontoserver/JDV
        - input/ontoserver/TRE
        - input/ontoserver/ASS
        - input/ontoserver/NamingSystem
    special-url-base: https://smt.esante.gouv.fr/fhir/
    special-url:
      - http://terminology.hl7.org/ValueSet/artifact-resource-types
pages:
    index.md:
        title: Accueil
    nos.md:
        title : NOS     
        NOS_MigrationNOSversSMTT0_01_PresDesNOSetSMT.md:
            title :   Présentation
        NOS_MigrationNOSversSMTT0_10_QuestCeQuneTRE.md:
            title :   TRE (définition)
        NOS_MigrationNOSversSMTT0_11_ProprietesDesTRE.md:
            title :   TRE (Propriété)
        NOS_MigrationNOSversSMTT0_12_CycleDeVieDesTRE.md:
            title :   TRE (Cycle de vie)
        NOS_MigrationNOSversSMTT0_20_QuestCeQunJDV.md:
            title :   JDV (définition)
        NOS_MigrationNOSversSMTT0_23_CycleDeVieDesJDV.md:
            title :   JDV (Cycle de vie)
        NOS_MigrationNOSversSMTT0_50_Publication.md:
            title :   Publication
        NOS_MigrationNOSversSMTT0_51_NommageDesNOS.md:
            title :   Nommage
        NOS_MigrationNOSversSMTT0_02_LaMigration.md:
            title :   Migration      
        NOS_MiseEnQualite_RepriseDesLibellesDesJDV.md:
            title :   Reprise des libellés     
        NOS_MiseEnQualiteCorrectionDuMappingNOSversFhir.md:
            title :   Mapping NOS to FHIR                                   
    tre.xml:
        title :  Terminologies 
        tre-smt.xml:
            title :  Terminologies   du SMT         
        tre-nos.xml:
            title :  Terminologies   du NOS          
        tre-deprecated.xml:
            title :  Terminologies  (Deprecated)  
        tre-retired.xml:
            title :  Terminologies  (Retired)           
        tre-telechargement.xml:
            title :  Terminologies (Téléchargement)      
    jdv.xml:
        title :  Jeux de valeurs 
        jdv-smt.xml:
            title :  Jeux de valeurs du SMT          
        jdv-cisis.xml:
            title :  Jeux de valeurs du CI-SIS               
        jdv-nos.xml:
            title :  Jeux de valeurs du NOS          
        jdv-deprecated.xml:
            title :  Jeux de valeurs (Deprecated)    
        jdv-retired.xml:
            title :  Jeux de valeurs (Retired)                
        jdv-telechargement.xml:
            title :  Jeux de valeurs (Téléchargement)            
    ass.xml:
        title :  Association 
        ass-telechargement.xml:
            title :  Association   
    namingSystem.xml:
        title :  namingSystem         
          
    autres_ressources.md:
        title: Autres Ressources
        telechargementNos.md:
            title :   téléchargement (NOS)           
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html         
    Terminologies  : tre.html
    Jeux de valeurs  : jdv.html
    Association  : ass.html    
#    NOS : 
#        Présentation : NOS_MigrationNOSversSMTT0_01_PresDesNOSetSMT.html
#       TRE (définition) : NOS_MigrationNOSversSMTT0_10_QuestCeQuneTRE.html
#        TRE (Propriété) : NOS_MigrationNOSversSMTT0_11_ProprietesDesTRE.html
#        TRE (Cycle de vie): NOS_MigrationNOSversSMTT0_12_CycleDeVieDesTRE.html
#        JDV (définition) : NOS_MigrationNOSversSMTT0_20_QuestCeQunJDV.html 
#        JDV (Cycle de vie) : NOS_MigrationNOSversSMTT0_23_CycleDeVieDesJDV.html
#        Publication : NOS_MigrationNOSversSMTT0_50_Publication.html
#        Nommage : NOS_MigrationNOSversSMTT0_51_NommageDesNOS.html
#        Migration : NOS_MigrationNOSversSMTT0_02_LaMigration.html    
#        Reprise des libellés : NOS_MiseEnQualite_RepriseDesLibellesDesJDV.html
#        Mapping NOS to FHIR   : NOS_MiseEnQualiteCorrectionDuMappingNOSversFhir.html       

    Ressources:
        Téléchargement (NOS) : telechargementNos.html
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html
